var openEl=document.getElementById("openMessage"),closeEl=document.getElementById("closeMessage"),fMessageEl=document.querySelector(".fMessage"),sMessageEl=document.querySelector(".sMessage"),messageEl=document.getElementById("message"),actualMessageEl=document.querySelector("#actualMessage"),fDarkModeEl=document.querySelector(".fDarkMode"),sDarkModeEl=document.querySelector(".sDarkMode"),onDEl=document.getElementById("onD"),offDEl=document.getElementById("offD"),bodyEl=document.getElementsByTagName("body")[0],
divEl=document.getElementsByTagName("div"),backSettingeEl=document.getElementById("backSettinge"),settingsEl=document.getElementById("settings"),accsettingsEl=document.getElementById("accSettings"),backAccEl=document.getElementById("backAcc"),accEl=document.getElementById("acc"),assEl=document.getElementById("ass"),closeWithEl=document.getElementById("closeWith"),withdrawalEl=document.getElementById("withdrawal"),withdrawEl=document.getElementById("withdraw"),backAboutEl=document.getElementById("backAbout"),
aboutEl=document.getElementById("about"),openAboutEl=document.getElementById("openAbout"),userNameEl=document.getElementById("userrName"),inputuserrNameEl=document.getElementsByClassName("username"),referEl=document.getElementById("refer"),backReferEl=document.getElementById("backRefer"),refFriendsEl=document.getElementById("refFriends"),bckCusEl=document.getElementById("bckCus"),contactEl=document.getElementById("contact"),cusServiceEl=document.getElementById("cusService"),bankAccEl=document.getElementById("bankAcc"),
bankAccountEl=document.getElementById("bankAccount"),backAccountEl=document.getElementById("backAccount"),investmentsEl=document.getElementById("investments"),conInvestEl=document.getElementById("conInvest"),backInvestEl=document.getElementById("backInvest"),fullNameEl=document.querySelectorAll(".fullName"),currentLevelEl=document.getElementsByClassName("currentLevel"),amntTocontributeEl=document.querySelectorAll(".amntTocontribute"),amntToReceiveEl=document.querySelectorAll(".amntToReceive"),recDurationEl=
document.querySelectorAll(".recDuration"),investEl=document.getElementById("invest"),userInfosEl=document.getElementById("userInfos"),userInfoEl=document.getElementById("userInfo"),backUseEl=document.getElementById("backUse"),changeUserNameEl=document.getElementById("changeUserName"),changeEmailAddressEl=document.getElementById("changeEmailAddress"),passChangeEl=document.getElementById("passChange"),chngUseNameEl=document.getElementById("chngUseName"),chngEmailEl=document.getElementById("chngEmail"),
chngPassEl=document.getElementById("chngPass"),bckPssChngEl=document.getElementById("bckPssChng"),bckEmailAddEl=document.getElementById("bckEmailAdd"),bckUserNameEl=document.getElementById("bckUserName");changeUserNameEl=document.getElementById("changeUserName");changeEmailAddressEl=document.getElementById("changeEmailAddress");passChangeEl=document.getElementById("passChange");
var codeEl=document.getElementById("code"),bckCodeEl=document.getElementById("bckCode"),fogPassEl=document.getElementById("fogPass"),investLEl=document.getElementById("investL"),remPassEl=document.getElementById("remPass"),bankEl=document.getElementById("bank"),bckDetEl=document.getElementById("bckDet"),addPo=document.getElementById("addPO"),ppsEl=document.getElementById("pps"),ppsEl1=document.getElementById("pps1"),passEl=document.getElementById("currentPassword"),logPassEl=document.getElementById("newPassword");
ppsEl.style.display="none";ppsEl1.style.display="none";passEl.oninput=function(){""!==passEl.value?(ppsEl.style.display="inline",ppsEl.onclick=function(){"password"==passEl.type?(passEl.type="text",ppsEl.setAttribute("class","fas fa-eye-slash")):(passEl.type="password",ppsEl.setAttribute("class","fas fa-eye"))}):ppsEl.style.display="none"};
logPassEl.oninput=function(){""!==logPassEl.value?(ppsEl1.style.display="inline",ppsEl1.onclick=function(){"password"==logPassEl.type?(logPassEl.type="text",ppsEl1.setAttribute("class","fas fa-eye-slash")):(logPassEl.type="password",ppsEl1.setAttribute("class","fas fa-eye"))}):ppsEl1.style.display="none"};$("#bank").hide(5);addPo.onclick=function(){$("#bank").show(1500)};bckDetEl.onclick=function(){$("#bank").hide(1500)};
for(var b=0,c=0,int=0,ints=0,userInt=0;userInt<inputuserrNameEl.length;){var bb=userNameEl.innerHTML;inputuserrNameEl[userInt].innerHTML=bb;userInt++}bckCodeEl.onclick=function(){codeEl.setAttribute("class","close")};fogPassEl.onclick=function(){codeEl.removeAttribute("class","close")};bckPssChngEl.onclick=function(){passChangeEl.setAttribute("class","close")};chngPassEl.onclick=function(){passChangeEl.removeAttribute("class","close")};
bckEmailAddEl.onclick=function(){changeEmailAddressEl.setAttribute("class","close")};chngEmailEl.onclick=function(){changeEmailAddressEl.removeAttribute("class","close")};bckUserNameEl.onclick=function(){changeUserNameEl.setAttribute("class","close")};chngUseNameEl.onclick=function(){changeUserNameEl.removeAttribute("class","close")};backUseEl.onclick=function(){userInfosEl.setAttribute("class","close")};userInfoEl.onclick=function(){userInfosEl.removeAttribute("class","close")};
backInvestEl.onclick=function(){investmentsEl.setAttribute("class","close")};investEl.onclick=function(){investmentsEl.removeAttribute("class","close")};bankAccEl.onclick=function(){bankAccountEl.removeAttribute("class","close")};backAccountEl.onclick=function(){bankAccountEl.setAttribute("class","close")};bckCusEl.onclick=function(){contactEl.setAttribute("class","close")};cusServiceEl.onclick=function(){contactEl.removeAttribute("class","close")};
backReferEl.onclick=function(){referEl.setAttribute("class","close")};refFriendsEl.onclick=function(){referEl.removeAttribute("class","close")};openAboutEl.onclick=function(){aboutEl.classList.remove("close")};backAboutEl.onclick=function(){aboutEl.classList.add("close")};assEl.onclick=function(){accsettingsEl.removeAttribute("class","close")};backAccEl.onclick=function(){accsettingsEl.setAttribute("class","close")};closeWith.onclick=function(){withdrawalEl.setAttribute("class","close")};
withdrawEl.onclick=function(){withdrawalEl.removeAttribute("class","close")};accEl.onclick=function(){settingsEl.removeAttribute("class","close")};backSettingeEl.onclick=function(){settingsEl.setAttribute("class","close")};offDEl.onclick=function(){sDarkModeEl.style.display="none";fDarkModeEl.style.display="block";for(bodyEl.setAttribute("class","dark");int<divEl.length;)divEl[int].classList.add("dark"),int++;ints=0};
onDEl.onclick=function(){sDarkModeEl.style.display="block";fDarkModeEl.style.display="none";for(bodyEl.removeAttribute("class","dark");ints<divEl.length;)divEl[ints].classList.remove("dark"),ints++;int=0};openEl.onclick=function(){sMessageEl.style.display="none";fMessageEl.style.display="block";messageEl.removeAttribute("class","close")};closeEl.onclick=function(){sMessageEl.style.display="block";fMessageEl.style.display="none";messageEl.setAttribute("class","close")};
function logout(){ajax_request.open("logout.php")};$("#conInvest").on('click', function(){investmentsEl.setAttribute("class","close"); $("#t_pane").show(1500); });$("#ct").on('click', function(){$("#t_pane").hide(1500)});$("#t_pane").hide(5);

